name: Build android app

on:
  push:
    branches: [ master ]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      SERVICE_APP_KEY: ${{ secrets.SERVICE_APP_KEY }}
      APPLICATION_NAME: TestMobileApp
      PACKAGE_NAME: com.companyname.testmobileapp
      CODEQL_ACTION_TESTING_ENVIRONMENT: codeql-action-pr-checks
      
    steps:
      - uses: actions/checkout@v3
      
       

      
      

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        

      - name: Build Solution
        run: msbuild ./${{ env.APPLICATION_NAME }}.sln /restore /p:Configuration=Release

      - name: Create and Sign the APK
        run: msbuild ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\${{ env.APPLICATION_NAME }}.Android.csproj /t:SignAndroidPackage /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: List folder content
        run: dir ${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\bin\Release
